{
    'extends': ['airbnb-base', 'prettier'],
    'plugins': ['prettier'],
    'env': { 'browser': true, 'es2020': true, 'node': true, 'jest': true },
    'parserOptions': { 'ecmaVersion': 11, 'sourceType': 'module' },
    'rules':
        {
            'quotes': [2, 'single', { 'avoidEscape': true }],
            'prettier/prettier': ['error'],
        },
}
